name: xxs
on:   
  push: 
  pull_request: 
  
jobs: 
 python-1: 
    runs-on: ubuntu-24.04-larger-arm
    timeout-minutes: 350
  
    steps: 
    - uses: actions/checkout@v4
    - name: ddsx
      continue-on-error: true 
      run: nproc
